version: "3"
services:
  db:
    image: "postgres:13"
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: "my_password"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine

  api:
    build: .
    ports:
    - 8000:8000
    command: poetry run uvicorn --host=0.0.0.0 app.main:app --reload
#    volumes:
#    - ./app:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: poetry run celery worker --app=app.core.worker.celery --loglevel=info --logfile=celery.log
#    volumes:
#    - ./app:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  flower:
    build: .
    command: poetry run flower --app=app.core.worker.celery --port=5555 --broker=redis://redis:6379/0
    ports:
    - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - worker



volumes:
  my_dbdata:


